title = "nschulzke"
description = "Explorations in language."

# The URL the site will be built for
base_url = "https://nschulzke.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feed = true

theme = "tale-zola"

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [
  {name = "tags", feed = true}, # each tag will have its own feed
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Nathan Schulzke"
github = "https://github.com/nschulzke"

katex = true

# Menu items
[[extra.menu]]
name = "Home"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"